source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'Hulk_Example' do
  platform :ios, '9.0'
  pod 'Hulk', :path => '../'

  target 'Hulk_Tests' do
    inherit! :search_paths

    
  end
end



target 'HulkServiceExtension' do 
    platform :ios, '10.0'
    pod 'HulkExtensionSDK'
end